[project]
name = "educative-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pandiarajan", email = "pandi.rajan@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "anthropic>=1.4.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
educative-examples = "educative_examples:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
